# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
   branches:
     master:
     - step:
        script:
        - echo On master push
     development:
     - step:
        script:
         - pipe: sonarsource/sonarcloud-scan:1.3.0
