# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2
clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly

pipelines:
   branches:
     master:
     - step:
        script:
        - echo On master push
     development:
     - step:
        script:
         - pipe: sonarsource/sonarcloud-scan:1.2.1
         - pipe: sonarsource/sonarcloud-quality-gate:0.1.4
